# Site settings
title: Harish Kadamudi
twitter_username: harishkadamudi
name: Harish Kadamudi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://techypark.wordpress.com/
 - title: GitHub
   url: https://github.com/harishkadamudi
 - title: StackOverflow
   url: http://stackoverflow.com/users/974065/harish-kadamudi
 - title: DZone
   url: https://dzone.com/users/756855/harishyouk.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/harishkadamudi
 - title: Docker Hub
   url: https://hub.docker.com/u/harishkadamudi

#Any buzzword skills you want to include
skills:
 - containers
 - Kubernetes
 - Docker
 - Kubernetes Operators
 - Envoy
 - Docker Compose
 - Hystrix
 - Micro Service Architecture
 - NGINX API
 - MongoDB
 - Golang
 - Spring JDBC
 - Spring MVC
 - Spring Boot
 - Spring Core
 - Spring Integration
 - Spring Security
 - Spring WebFlow
 - Spring REST
 - REST
 - Hibernate
 - Activiti Workflow
 - JBoss BPM
 - Java
 - J2EE
 - Ext Js
 - Javascript
 - Oracle
 - DB2
 - MySQL
 - MSSQL
 - JBOSS
 - WebLogic
 - WebSphere
 - Apahce Tomcat
 - TestNG
 - Junit
 - DBUnit

#Blogfeed is optional - including this will add JS to call the feed and populate blog list


#Work experience is required
roles:
 - title: Lead Software Engineer
   start: May 2017
   end: ongoing
   employer: JP Morgan Service India Private Limited
   description: JP Morgan Service India Private Limited
 - title: Module Lead
   start: Jan 2015
   end: May 2017
   employer: Nous Info System.
   description: <a target='_blank' href='http://www.foliodynamix.com'>FolioDynamix</a> is leading the evolution of the wealth management experience, with an end-to-end technology solution paired with a suite of advisory tools including model portfolios, research, and overlay management services.
 - title: Senior Software Engineer
   start: June 2013
   end: Nov 2015
   employer: HCL Technologies.
   description: Deutsche Bank.
 - title: Software Engineer
   start: Aug 2010
   end:  May 2013
   employer: Core Business Software Solutions.
   description: Benir E-Store Solutions.
   
#Roles and Responsibilites
Responsibilites:
 
 - Responsible for Architecturing Legacy Application(Multi page application) to Advisory Portal Application(Single Page Application) using REST architecture and Ext JS 6.0.
 - Designing REST API Design - Resource Modelling.
 - Document REST API using Swagger framework.
 - Writing modular application and following Sonar Reports to close project finding.
 - Branding the application to be used by Many clients, with different deployment types like shared and dedicated environments.
 - Wrote ANT scripts to support client requirements for Branding the application and deployments.
 - Requirement gathering through JIRA, and follow JIRA life cycle in Analysing, Clarification, Estimating, and Developing the requirement.
 - Coordinate with internal and external resources as necessary, Familiarise the team with the customer needs, specifications, design targets, the development process, design standards,
   techniques and tools to support task performance
 - Ensure deliverable are prepared to satisfy the project requirements, cost and schedule and Help keep the team focused and on track.
 - Provide status reporting of team activities against the program plan or schedule, Keep the project manager and product committee informed of task accomplishment, issues and status

 
#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2009
   subject: Electronic & Communication.
   school: KNSIT

#This section is optional (as is the image link below)
#coursera:
  # profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   #courses:
    #- title: Functional Programming Principles in Scala
     # link: https://www.coursera.org/course/progfun
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
    #- title: Algorithms Design and Analysis, Part 1
     # link: https://www.coursera.org/course/progfun
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      #date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - harishkadamudi/client-go-example
 - harishkadamudi/aws-eks-kubernetes-masterclass 
 - harishkadamudi/client-go-demo 
 - harishkadamudi/opa-istio-policy
 - harishkadamudi/sapt
 - harishkadamudi/kube-mutating-webhook-tutorial 
 - harishkadamudi/minimal-opa-envoy-example
 - harishkadamudi/sidecar-injector
 - harishkadamudi/kubernetes-handbook
 - harishkadamudi/spring-boot-data-jpa-mysql-docker-composer
 - harishkadamudi/spring-boot-data-source-decorator 
 - harishkadamudi/angular-spring-dynamic-form 
 - harishkadamudi/notes 
 - harishkadamudi/HarishExamples
 - harishkadamudi/spring-mongodb
 - harishkadamudi/spring-multi-model
 - harishkadamudi/spring-elk
 - harishkadamudi/hystrix-examples
 - harishkadamudi/spring-cloud-netflixOS-stack
 - harishkadamudi/jenkins_ws
 - harishkadamudi/Maven-Example
 - harishkadamudi/ScalaExamples
 - harishkadamudi/jms
 - harishkadamudi/spring-integration-samples
 - harishkadamudi/SpringExtJs
 

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/974065/harish-kadamudi
   flairimageurl: http://stackoverflow.com/users/flair/974065.png


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Cloud Platforms</strong>: Proficiency in cloud platforms such as Amazon Web Services (AWS), GKP (self-hosted). Understanding the core services, infrastructure, and management capabilities of the chosen cloud platform is essential.<br/><br/>
   <strong>Infrastructure-as-a-Service (IaaS)</strong>: Experience with Infrastructure-as-Code tools like Terraform or Ansible for provisioning and managing infrastructure resources required by Kubernetes, including virtual machines, storage, and networking.<br/><br/>
   <strong>Platform-as-a-Service (PaaS)</strong>: Familiarity with PaaS offerings, such as AWS Elastic Beanstalk, or Google App Engine, and the ability to deploy, manage, and scale applications on these platforms.<br/><br/>
   <strong>Software-as-a-Service (SaaS)</strong>: Understanding of SaaS models and experience working with cloud-based software applications and services.<br/><br/>
   <strong>Infrastructure as Code (IaC)</strong>: Experienced in working with tools such as Terraform, CloudFormation, Infrastructure Abstraction, Configuration Management.<br/><br/>
   <strong>Developer Experience (DX)</strong>:  Documentation, SDKs and Tooling, Sample Code and Tutorials, Community and Support, Integration and Interoperability, Continuous Improvement and Iterative Improvement.<br/><br/>
   <strong>Cloud Security</strong>: Knowledge of cloud security best practices, including identity and access management (IAM), encryption, network security groups, and security monitoring in the cloud environment.<br/><br/>
   <strong>Serverless Computing</strong>: Proficiency in serverless computing concepts and experience with serverless platforms like AWS Lambda, for building event-driven, scalable, and cost-effective applications.<br/><br/>
   <strong>Containers and Orchestration</strong>: Knowledge of containerization technologies such as Docker and container orchestration platforms like Kubernetes for building and managing containerized applications in the cloud.<br/><br/>
   <strong>Kubernetes</strong>: Expertise in Kubernetes, including in-depth knowledge of its architecture, components, and core concepts such as pods, deployments, services, ingress, persistent volumes, and namespaces.<br/><br/>
   <strong>Kubernetes Operators</strong>: Familiarity with Kubernetes Operators, which enable the automation of complex application management tasks, and the ability to design and develop custom Operators using tools like Operator SDK.<br/><br/>
   <strong>Hybrid and Multi-cloud Environments</strong>: Experience in designing and managing hybrid cloud or multi-cloud environments, including integrating on-premises infrastructure with cloud resources and managing cloud services across multiple providers.<br/><br/>
   <strong>Programming Languages</strong>: Expertise in one or more programming languages, such as Java (spring framework), Golang, NodeJs, Python, JavaScript and Ruby, with a deep understanding of language-specific features, syntax, and best practices.<br/><br/>
   <strong>Database Design and Management</strong>: Experience in designing and working with relational databases (e.g., MySQL, PostgreSQL, Oracle) or NoSQL databases (e.g., MongoDB, Redis), including data modeling, indexing, query optimization, and database administration.<br/><br/>
   <strong>Software Security</strong>: Knowledge of software security principles, secure coding practices, and common vulnerabilities (e.g., OWASP Top 10) to develop secure and resilient software applications.<br/><br/>
   <strong>API Development</strong>: Knowledge of designing and building RESTful or GraphQL APIs, including API documentation, versioning, authentication, and authorization mechanisms.<br/><br/>
   <strong>JVM</strong>: I am experienced in a variety of Java APIs and frameworks. I have extensively worked on Spring MVC, Spring Boot, Hibernate frameworkds. <br/><br/>
   I have rich set of experience in designing and developing Microservice application using frameworks like nginx, Ribbon,Spring Boot and containers like Docker & Docker Compose.<br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC/REST framework. I have also worked with client side technology, having used Ext JS, Javascript, Angular2,jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git,CVS, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as Amazon AWS/CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   <strong>Testing and Quality Assurance</strong>: Expertise in various testing methodologies, including unit testing, integration testing, and automated testing frameworks (e.g., JUnit, NUnit, Selenium), to ensure software quality and reliability.<br/><br/>
   <strong>Project Management</strong>: Familiarity with project management methodologies and tools, including task management, agile boards (e.g., Jira, Trello), and project tracking, to effectively plan, prioritize, and deliver software projects. <br/><br/>
   <strong>Certification</strong>: Certified AWS solution Architect and MongoDB Certified Developer. <br></br>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://techypark.wordpress.com/">https://techypark.wordpress.com/</a>.
