# Site settings
title: Harish Kadamudi
twitter_username: harishkadamudi
name: Harish Kadamudi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://techypark.wordpress.com/
 - title: GitHub
   url: https://github.com/harishkadamudi
 - title: StackOverflow
   url: http://stackoverflow.com/users/974065/harish-kadamudi
 - title: DZone
   url: https://dzone.com/users/756855/harishyouk.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/harishkadamudi

#Any buzzword skills you want to include
skills:
 - Docker
 - Docker Compose
 - Hystrix
 - Micro Service Architecture
 - NGINX API
 - MongoDB
 - Spring JDBC
 - Spring MVC
 - Spring Boot
 - Spring Core
 - Spring Integration
 - Spring WebFlow
 - Spring REST
 - REST
 - Hibernate
 - Activiti Workflow
 - JBoss BPM
 - Java
 - J2EE
 - Ext Js
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list


#Work experience is required
roles:
 - title: Module Lead
   start: Jan 2015
   end: Ongoing
   employer: Nous Info System.
   description: FolioDynamix is leading the evolution of the wealth management experience, with an end-to-end technology solution paired with a suite of advisory tools including model portfolios, research, and overlay management services.

#Roles and Responsibilites
Responsibilites:
 - Responsible for Architecturing Legacy Application(Multi page application) to Advisory Portal Application(Single Page Application) using REST architecture and Ext JS 6.0.
 - Designing REST API Design - Resource Modelling.
 - Document REST API using Swagger framework.
 - Writing modular application and following Sonar Reports to close project finding.
 - Branding the application to be used by Many clients, with different deployment types like shared and dedicated environments.
 - Wrote ANT scripts to support client requirements for Branding the application and deployments.
 - Requirement gathering through JIRA, and follow JIRA life cycle in Analysing, Clarification, Estimating, and Developing the requirement.
 - Coordinate with internal and external resources as necessary, Familiarise the team with the customer needs, specifications, design targets, the development process, design standards,
   techniques and tools to support task performance
 - Ensure deliverable are prepared to satisfy the project requirements, cost and schedule and Help keep the team focused and on track.
 - Provide status reporting of team activities against the program plan or schedule, Keep the project manager and product committee informed of task accomplishment, issues and status

 
#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2009
   subject: Electronic & Communication.
   school: KNSIT

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - harishkadamudi/spring-integration-samples
 - harishkadamudi/HarishExamples
 - harishkadamudi/spring-mongodb
 - harishkadamudi/spring-multi-model
 - harishkadamudi/spring-elk
 - harishkadamudi/hystrix-examples
 - harishkadamudi/spring-cloud-netflixOS-stack
 - harishkadamudi/jenkins_ws
 - harishkadamudi/Maven-Example
 - harishkadamudi/ScalaExamples
 - harishkadamudi/jms
 - harishkadamudi/spring-integration-samples
 - harishkadamudi/SpringExtJs
 

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/974065/harish-kadamudi
   flairimageurl: http://stackoverflow.com/users/flair/974065.png


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have extensively worked on Spring MVC, Spring Boot, Hibernate frameworkds.
   I have rich set of experience in designing and developing Microservice application using frameworks like nginx, Ribbon,Spring Boot and containers like Docker & Docker Compose.<br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC/REST framework. I have also worked with client side technology, having used Ext JS, jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://techypark.wordpress.com/">https://techypark.wordpress.com/</a>.
