# Site settings
title: Harish Kadamudi
twitter_username: harishkadamudi
name: Harish Kadamudi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://techypark.wordpress.com/
 - title: GitHub
   url: https://github.com/harishkadamudi
 - title: StackOverflow
   url: http://stackoverflow.com/users/974065/harish-kadamudi
 - title: DZone
   url: https://dzone.com/users/756855/harishyouk.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/harishkadamudi
 - title: Docker Hub
   url: https://hub.docker.com/u/harishkadamudi

#Any buzzword skills you want to include
skills:
 - containers
 - Kubernetes
 - Docker
 - Kubernetes Operators
 - Envoy
 - Docker Compose
 - Hystrix
 - Micro Service Architecture
 - NGINX API
 - MongoDB
 - Golang
 - Spring JDBC
 - Spring MVC
 - Spring Boot
 - Spring Core
 - Spring Integration
 - Spring Security
 - Spring WebFlow
 - Spring REST
 - REST
 - Hibernate
 - Activiti Workflow
 - JBoss BPM
 - Java
 - J2EE
 - Ext Js
 - Javascript
 - Oracle
 - DB2
 - MySQL
 - MSSQL
 - JBOSS
 - WebLogic
 - WebSphere
 - Apahce Tomcat
 - TestNG
 - Junit
 - DBUnit

#Blogfeed is optional - including this will add JS to call the feed and populate blog list


#Work experience is required
roles:
 - title: Lead Software Engineer
   start: May 2017
   end: Ongoing
   employer: JP Morgan Service India Private Limited
   description: JP Morgan Service India Private Limited
 - title: Module Lead
   start: Jan 2015
   end: May 2017
   employer: Nous Info System.
   description: <a target='_blank' href='http://www.foliodynamix.com'>FolioDynamix</a> is leading the evolution of the wealth management experience, with an end-to-end technology solution paired with a suite of advisory tools including model portfolios, research, and overlay management services.
 - title: Senior Software Engineer
   start: June 2013
   end: Nov 2015
   employer: HCL Technologies.
   description: Deutsche Bank.
 
 - title: Software Engineer
   start: Aug 2010
   end: May 2013
   employer: Core Business Software Solutions.
   description: Benir E-Store Solutions.
   
#Roles and Responsibilites
Responsibilites:
  -	Design, deploy, and manage our cloud infrastructure using leading cloud platforms such as Amazon Web Services (AWS), GKP (self-hosted), or EKS (AWS).
  -	Design, develop, and deploy backend services and applications using the Java/Go/NodeJs programming language.
  -	Collaborate with product managers, designers, and other developers to understand requirements and translate them into technical solutions.
  -	Write clean, efficient, and maintainable code that follows best practices and coding standards.
  -	Implement and maintain unit tests and integration tests to ensure code quality and reliability.
  -	Optimize application performance and scalability through profiling, tuning, and code refactoring.
  -	Provide strategic guidance on cloud architecture, microservices, containerization, and serverless computing to drive innovation and efficiency.
  -	Collaborate with cross-functional teams to integrate software components and ensure smooth system integration.
  -	Develop and implement cloud-based architectures, including networking, storage, compute, and security components, to meet the needs of our applications and services.
  -	Optimize the performance and cost-efficiency of cloud resources by leveraging cloud-native services and applying industry best practices.
  -	Collaborate with development teams to define and implement cloud deployment strategies, including continuous integration/continuous deployment (CI/CD) pipelines.
  -	Monitor and troubleshoot cloud infrastructure to ensure high availability, reliability, and performance.
  -	Implement security measures to protect cloud-based resources, including identity and access management, encryption, and security monitoring.
  -	Collaborate with cross-functional teams, including developers, system administrators, and network engineers, to drive effective cloud integration and interoperability.
  -	Document technical procedures, guidelines, and best practices related to cloud infrastructure and operations.
  -	Participate in Agile/Scrum development practices, including sprint planning, stand-up meetings, and retrospectives.
  -	Being a part of efft-cloud engineering, we were the first one to adopt hybrid cloud strategy within EFP, running successfully since 2017.
  -	Evaluating Kubernetes with various business cases to adopt containers.
  -	In POC stage, we have picked up existing business applications and containerized it and evaluating Kubernetes as a platform to extra the benefits of container ecosystem (GKS).
  -	Built design/architecture plans and enhance existing solutions to migrate or to adopt cloud and contribute to the design of the target Hosting & Operations model according to the business needs.
  -	Customized Service Discovery (eureka server), API gateway (Zuul Server) to suite hybrid cloud computing, i.e. to run on platforms like Physical/virtual boxes and GAIA (cloud foundry).
  -	Successfully migrated over 50+ applications across Principal Lending (Equities) and Agency Lending (Investor Service).
  -	Built common module using spring-boot to eliminate common configuration in client applications.
  -	Enhanced Zuul for request tracing and tracing the Instance served the request along with time taken to respond.
  -	Enhanced Zipkin to trace Apache http client requests, by default Sleuth instrument only Rest Client.
  -	Early adopters of Jules(CD/CI tool), contributed to GAIA (cloud foundry) AIM deployment.
  -	Collaborated with SRE in building common module, ex. oracle Tracing System

 
#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2009
   subject: Electronic & Communication.
   school: KNSIT

#This section is optional (as is the image link below)
#coursera:
  # profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   #courses:
    #- title: Functional Programming Principles in Scala
     # link: https://www.coursera.org/course/progfun
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
    #- title: Algorithms Design and Analysis, Part 1
     # link: https://www.coursera.org/course/progfun
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      #date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - harishkadamudi/HarishExamples
 - harishkadamudi/spring-mongodb
 - harishkadamudi/spring-multi-model
 - harishkadamudi/spring-elk
 - harishkadamudi/hystrix-examples
 - harishkadamudi/spring-cloud-netflixOS-stack
 - harishkadamudi/jenkins_ws
 - harishkadamudi/Maven-Example
 - harishkadamudi/ScalaExamples
 - harishkadamudi/jms
 - harishkadamudi/spring-integration-samples
 - harishkadamudi/SpringExtJs
 

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/974065/harish-kadamudi
   flairimageurl: http://stackoverflow.com/users/flair/974065.png


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |

  Nearly <strong>13 years of experience</strong> in requirement analysis, software design, development, implementation, support and management for software like Banking Finance Wealth Management, Real Estate and Insurance Solutions, Strategic Enterprise Solutions, Micro Services Architecture, Multi-Tier Distributed Architecture, e-Commerce / internet applications
  Highly accomplished senior engineer with extensive expertise in cloud adoption, architectural design, and data operations. With a proven track record of delivering exceptional technical solutions. I possess the skills, experience, and insights to seamlessly transition applications, computing platforms, and data operations to the cloud. 
  Certified AWS solution Architect and MongoDB Certified Developer. <br/><br/>
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have extensively worked on Spring MVC, Spring Boot, Hibernate frameworkds.
   I have rich set of experience in designing and developing Microservice application using frameworks like nginx, Ribbon,Spring Boot and containers like Docker & Docker Compose.<br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC/REST framework. I have also worked with client side technology, having used Ext JS, Javascript, Angular2,jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git,CVS, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as Amazon AWS/CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://techypark.wordpress.com/">https://techypark.wordpress.com/</a>.
